name: main

on: [pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run e2e tests 🧪
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:ci
